name: Release

# manual only kick off
on:
  
  push:
    branches:
      - master
      - oss-release

  workflow_dispatch:

jobs:
  release:
    runs-on: windows-latest 

    steps:
      
      - name: ⬇️ Download artifacts from latest workflow
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build.yml
          workflow_conclusion: success

      # https://github.com/softprops/action-gh-release
      #- name: create gh release
      #  uses: softprops/action-gh-release@v1
      #  if: github.ref == 'refs/heads/master'
      #  with:
      #    tag_name: ${{ env.VERSION }}
      #    name: ${{ env.VERSION }}
      #    files: |
      #      bin/*.msi
      #      bin/*.zip
      #    generate_release_notes: true

      - name: debug
        run: ls -R
        working-directory: .
