name: Release

# manual only kick off
on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest 

    steps:
      
      - name: ⬇️ Download artifacts from latest workflow
        uses: dawidd6/action-download-artifact@v6
        with:
          name: bin-static
          workflow: build.yml
          workflow_conclusion: success

      - name: 🔍 view artifacts to be used
        run: ls -R
        working-directory: .

      - name: 🔢 set version environment variable
        run: |
          echo "VERSION=$(cat version.txt | xargs)" >> "$GITHUB_ENV"

      - name: 🔢 prep release notes
        run: |
          envsubst < instructions.md > g.tmp && mv g.tmp instructions.md
          grep -m 2 -B 1000 '^## ' release-notes.md | tail -n +3 | head -n -2 > final_notes.md
          cat instructions.md >> final_notes.md
          cat final_notes.md
          

      # https://github.com/softprops/action-gh-release
      - name: 📦 create release
        uses: softprops/action-gh-release@v1
        if: github.ref == 'refs/heads/master'
        with:
          tag_name: ${{ env.VERSION }}
          name: ${{ env.VERSION }}
          files: |
            bt-*.*
          body_path: final_notes.md
